owner: 6af # GitHub username
repo: uptime # GitHub repository name
sites: # List of endpoints to track
  - name: 6afs website 
    url: https://devloper6af.gq/
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website: # Status website (optional)
  cname: uptime.devloper6af.gq # Custom domain CNAME
  name: Uptime # Status website title
